extends:
  - 'typescript-shareable'

parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 2019
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true
  node: true

settings:
  react:
    version: detect

rules:
  ### eslint-plugin-import
  'import/no-cycle': off

overrides:
  ###
  # Test file overrides
  ###
  - files: ['**/*.test.tsx', '**/*.test.ts']
    env:
      jest: true
