changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

enableGlobalCache: false

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint: "*"
      eslint-import-resolver-node: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
